import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navebar, { NavebarItem } from "./componentes/Navebar";
import MainLayout from "./componentes/MainLayout";
import {
  House,
  Blocks,
  ChartNoAxesCombined,
  LayoutDashboard,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const tamaño = {
  sidebar: 25,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen`}>
        <Providers>
          
            <div className="flex min-h-screen">
              <Navebar>
                <NavebarItem icon={<House size={tamaño.sidebar} />} text="Inicio" active href="/apps/Menu" />
                <NavebarItem icon={<Blocks size={tamaño.sidebar} />} text="Stock" href="/apps/ProductosYServicios" />
                <NavebarItem icon={<ChartNoAxesCombined size={tamaño.sidebar} />} text="Ventas" href="/apps/Ventas" />
                <NavebarItem icon={<LayoutDashboard size={tamaño.sidebar} />} text="Reportes" href=""/>
              </Navebar>
              <MainLayout>{children}</MainLayout>
            </div>
          
        </Providers>
      </body>
    </html>
  );
}
